### ISSUE TITLE
AV2 public online leaderboard result

### ISSUE THREAD

**Issue by Kin-Zhang** [yanconglin/ICP-Flow#1]
Thanks for your work!

Since you use av2 in the paper and the same task for the av2 self-supervised leaderboard, I'm wondering if you have any _public_ results **in the online leaderboard**? could you share your result/score file in the public leaderboard? like this thread: [https://github.com/KTH-RPL/DeFlow/discussions/2](https://github.com/KTH-RPL/DeFlow/discussions/2)

link: https://eval.ai/web/challenges/challenge-page/2010/leaderboard/4759

Looking forward to your reply.

**Comment by yanconglin** [comment]
Thank you for your interest.
I do not have yet results on the Argoverse 2.0 Self-Supervised Scene Flow benchmark at this moment.

**Comment by Kin-Zhang** [comment]
I see, looking forward to your result then. 
I will keep this open until we have the result. If you are busy I will help when you open-source with pre-trained weight

Thanks!

**Comment by dailing57** [comment]
Wonderful work! Is the av2 data set you are using Argoverse 2 Sensor Dataset?

**Comment by yanconglin** [comment]
yes, you are right.

**Comment by yanconglin** [comment]
Results are available on the AV2 Scene Flow Challenge Leaderboard.
