### ISSUE TITLE
Inference on my dataset

### ISSUE THREAD

**Issue by Filippoghilo** [yanconglin/ICP-Flow#2]
Hi, thank you for your work and for making it available for use. I would be really interested in using your method for flow estimation on a personal dataset, but I can't really grasp what kind of preprocesing you did on the public datasets. I understand that you need to remove ground point and correct ego motion, but I don't get if you are using other annotations or stuff for testing: I would be really grateful if you can give an hint on what else would I need a part from these "cleaned" pointclouds and if I can effectively run this method on another dataset. Thank you for your help!

**Comment by yanconglin** [comment]
To test on a custom dataset, I would say first run a few test samples to visually examine the result and adjust the hyperparameters (if needed). There is no need for annotation or other stuff for inference.

Perhaps you can share with me some details on your data?

**Comment by Filippoghilo** [comment]
Thank you for the quick answer! what hyperparameters do you refer to? I see there are some flags with ranges and threshold, but those are for Waymo and nuscenes.
My data are some scans from a Velodyne vls128 in a urban environment, my ranges are similar to yours in x and y but the number of points is way different

**Comment by yanconglin** [comment]
I would recommend trying the default parameters used on waymo and manually checking some samples. Pay attention to those failure cases and tune the parameters accordingly. Since the entire approach is fully hand-crafted, you can visualize each intermediate step. Regarding the vls-128 lidar, I would assume you may need to play with the clustering parameters.

**Comment by Filippoghilo** [comment]
Thank you for the help. Do I need to run the main.sh or the demo.sh to estimate flow? I'm not 100% sure and since I have .bin files I have to transform them in npz or rework the code I want to be sure of what I need. Ground truth pose is also something I can avoid having since with kiss_icp flag I can estimate it, is it correct?

**Comment by Filippoghilo** [comment]
Okay I see so I just have to motion compensate my sequence, remove ground points beforehand and basically save two scans together in a npz file like in waymo/argoverse datasets right? Thank you again for all these clarifications
