### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by zengCSDN** [yanconglin/ICP-Flow#3]
Thanks for your open source work! How do you process the nuscenes and waymo datasets into a data format that can be trained and tested.

**Comment by yanconglin** [comment]
Please refer to [Dynamic 3D Scene Analysis by Point Cloud Accumulation](http://arxiv.org/abs/2207.12394) for details. I have mentioned in the paper that the waymo/nuscenes scene flow datasets come from this repository.

**Comment by zengCSDN** [comment]
Thank you for response!
