### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by zengCSDN** [yanconglin/ICP-Flow#4]
Hi, I used metrics_waymo_test_240421-140450/npz for the visualization, but I got an error. Then I printed the information inside and found that it was inconsistent with the information in demo.npz. May I ask how did you generate the file demo.npz? The saved result after I conducted main.sh reasoning with waymo and nuscenes was inconsistent with the content of demo.npz you provided. Looking forward to your reply!

**Comment by yanconglin** [comment]
Datasets have different conventions in terms of data structure. It is hard to provide a demo code that works for all. Feel free to adapt the demo.py or main.py to fit the customized or various datasets.

**Comment by zengCSDN** [comment]
Ok, I see. Thanks again for your reply
