### ISSUE TITLE
GPU memory overflows: when batch size is large!

### ISSUE THREAD

**Issue by zengCSDN** [yanconglin/ICP-Flow#5]
Hi, When I was running main.py, the application stuck, and then I located the problem "from utils_track import track"，Locate further to
    # bug there: when batch size is large!
    t_hist = hist(dst, src, 
                  bins_x.min(), bins_y.min(), bins_z.min(),
                  bins_x.max(), bins_y.max(), bins_z.max(),
                  len(bins_x), len(bins_y), len(bins_z))

How did you solve the problem?  Looking forward to your reply!

**Comment by yanconglin** [comment]
I see. The easiest solution is to reduce the batch size or decrease arg.max_points. I did all experiments on v100(32GB) and RTX6000 (48GB), so the GPU RAM is large enough to handle some extraordinary cases. What GPUs are you using?

**Comment by zengCSDN** [comment]
The GPU I use is RTX3090(24G), there is a problem is that after I adjusted the code, the program has been stuck, and later found that it is necessary to delete the hist_cuda/cpp/build and recompile, but I can only run two frame point cloud after compilation, and then stuck, what is the reason?

**Comment by yanconglin** [comment]
Thank you for the update. I have provided a hack [there](https://github.com/yanconglin/ICP-Flow/blob/dc9403904ece9468a8f79e6c80ac0e41d5f26e77/utils_hist.py#L112) to solve the high memory consumption issue. 
I will also do a full test later.

**Comment by zengCSDN** [comment]
Hi, HIST.hist This step is very time-consuming, and requires a large memory, the entire data set can only run the first few frames, can not complete the data set to run the whole way, what optimization method, supposedly after processing each frame, should release the memory, rather than apply for new memory.

Error reported as follows:
2024-04-29 16:40:26 [ERROR] [ -4280403,Out of memory ] cuMemAlloc_v2(): fail to allocate 630573056 KB memory (out of memory)
2024-04-29 16:40:26 [ERROR] [ -4280403,Out of memory ] cuMemAlloc_v2(): fail to allocate 630573056 KB memory (out of memory)
Traceback (most recent call last):
  File "/ICP-Flow/main.py", line 323, in <module>
    pairs, transformations = track(args, point_src, point_dst, label_src, label_dst)
  File "/ICP-Flow/utils_track.py", line 32, in track
    pairs, transformations = match_pcds(args, point_src, point_dst, label_src, label_dst) 
  File "/ICP-Flow/utils_match.py", line 57, in match_pcds
    pairs_dyn, transformations_dyn = match_pairs(args, src_points, dst_points, src_labels, dst_labels, pairs_true) 
  File "/ICP-Flow/utils_match.py", line 92, in match_pairs
    transformations = hist_icp(args, segs_src, segs_dst)
  File "/ICP-Flow/utils_match.py", line 149, in hist_icp
    init_poses_ = estimate_init_pose(args, src_, dst_) 
  File "/ICP-Flow/utils_hist.py", line 54, in estimate_init_pose
    t_hist = hist(dst, src, 
  File "/ICP-Flow/hist_cuda/hist.py", line 45, in hist
    histogram = HIST.hist(X, Y, 
RuntimeError: CUDA out of memory. Tried to allocate 601.36 GiB (GPU 0; 23.86 GiB total capacity; 105.11 MiB already allocated; 22.54 GiB free; 128.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Thanks you for your reply!

**Comment by zengCSDN** [comment]
> Thank you for the update. I have provided a hack [there](https://github.com/yanconglin/ICP-Flow/blob/dc9403904ece9468a8f79e6c80ac0e41d5f26e77/utils_hist.py#L112) to solve the high memory consumption issue. I will also do a full test later.

Thank you so much for your wonderful work!

**Comment by yanconglin** [comment]
Simply decrease the value of [chunk](https://github.com/yanconglin/ICP-Flow/blob/dc9403904ece9468a8f79e6c80ac0e41d5f26e77/utils_hist.py#L115). The logic is like this:
Imagine there are N pairs of clusters, after ground removal and clustering. Feeding all of them into utils_hist would result in a giant tensor of N x H x W x D, where H/W/D is the size of the histograms, respectively. To reduce the memory consumption, you can simply split the N pairs into multiple chunks of size C and run ultils_hist multiple times, such that each time the memory consumption is only C/N x H x W x D. Of course the consequence is that it consumes more time. You may need to adjust C according to your GPU type.

**Comment by zengCSDN** [comment]
> Simply decrease the value of [chunk](https://github.com/yanconglin/ICP-Flow/blob/dc9403904ece9468a8f79e6c80ac0e41d5f26e77/utils_hist.py#L115). The logic is like this: Imagine there are N pairs of clusters, after ground removal and clustering. Feeding all of them into utils_hist would result in a giant tensor of N x H x W x D, where H/W/D is the size of the histograms, respectively. To reduce the memory consumption, you can simply split the N pairs into multiple chunks of size C and run ultils_hist multiple times, such that each time the memory consumption is only C/N x H x W x D. Of course the consequence is that it consumes more time. You may need to adjust C according to your GPU type.

There seems to be a similar problem. If I set chunk to 10, the program will get stuck for a long time and then time out.
Application will exit soon because it is idle for more than 5400 seconds which is set by env "ORION_TASK_IDLE_TIME".

**Comment by zengCSDN** [comment]
Hi, May I ask what these parameters stand for.
hist cuda params:  torch.Size([10, 5000, 4]) torch.Size([10, 5000, 4]) tensor(-645.2766) tensor(-645.2766) tensor(-0.1000) tensor(645.3235) tensor(645.3235) tensor(0.1000) 12907 12907 3

print('hist cuda params: ', X.shape, Y.shape,
          min_x, min_y, min_z,
          max_x, max_y, max_z,
          len_x, len_y, len_z,
          )

**Comment by yanconglin** [comment]
I have tested on my machine with chunk_size=10 and it works. 
hist cuda parameters: I would assume you are referring to this [line]( https://github.com/yanconglin/ICP-Flow/blob/835b46a4d19816f11d76c0aa8dfe7dd94236b579/hist_cuda/hist.py#L40). X.shape is the size of batched clusters, meaning there are 10 clusters, 5000 points each cluster and 4 scalars per point (x/y/z/padding); min_x and max_x are the maximal translation along x dimension (in meters); len_x is the x dimension of the output histogram. 
Clearly, some parameters you are using do not make sense. The max_x and min_x is +/-645.2766 meters. This is simply not possible. I see the reason why you have the memory issue there. please double check the configurations in the .sh file.

**Comment by zengCSDN** [comment]
> I have tested on my machine with chunk_size=10 and it works.
> 
> hist cuda parameters: I would assume you are referring to this [line](https://github.com/yanconglin/ICP-Flow/blob/835b46a4d19816f11d76c0aa8dfe7dd94236b579/hist_cuda/hist.py#L40). X.shape is the size of batched clusters, meaning there are 10 clusters, 5000 points each cluster and 4 scalars per point (x/y/z/padding); min_x and max_x are the maximal translation along x dimension (in meters); len_x is the x dimension of the output histogram. Please refer to [this line](https://github.com/yanconglin/ICP-Flow/blob/835b46a4d19816f11d76c0aa8dfe7dd94236b579/utils_hist.py#L63).
> 
> Clearly, some parameters you are using do not make sense. The max_x and min_x is +/-645.2766 meters. This is simply not possible. I see the reason why you have the memory issue there. Please double-check the configurations in the .sh file. The code has been updated and please git pull as well.

Ok, I see. I use personal data. It may be that the method I use when generating test data is not normal, which poses that the ego_poses and speed do not have the correct Settings, while the deviation from translation_frame is too large. I will check my data generation method in detail, thank you very much for your wonderful answer!
