### ISSUE TITLE
Which model is used for FNN

### ISSUE THREAD

**Issue by MohamedRamzy1** [yanconglin/ICP-Flow#6]
Thanks a lot for sharing that great work! I have a question, I know that you used ZeroFlow for the FNN.

Could you please share which config file in ZeroFlow repo did you use and how to load your pretrained checkpoints ?

**Comment by yanconglin** [comment]
1. config files are the same as FastFlow/ZeroFlow; 2. replace the FastFlow/ZeroFlow checkpoints with my own.

**Comment by MohamedRamzy1** [comment]
Could you please give me a link for these config files ?

**Comment by yanconglin** [comment]
If not mistaken, [configs/fastflow3d/argo/nsfp_distilatation.py](https://github.com/kylevedder/zeroflow/blob/master/configs/fastflow3d/argo/nsfp_distilatation.py)

**Comment by yanconglin** [comment]
![Screenshot from 2024-06-11 13-04-33](https://github.com/yanconglin/ICP-Flow/assets/26435516/8cb951df-6c15-4a04-8f8d-bb5883ecf19d)
The config I used during training/testing.
