### ISSUE TITLE
Inference using unsupervised ICP-Flow

### ISSUE THREAD

**Issue by BotaoSun** [yanconglin/ICP-Flow#7]
Hi, thanks for your excellent work on the LiDAR scene flow estimation.

I would like to ask what I should do if I just want to use the unsupervised method to infer my consecutive LiDAR PCs. In these consecutive LiDAR PCs, I don't have any labels, so I don't want to evaluate the metrics.

If I don't misunderstand, I don't need checkpoints for this process. What I should do is first compensate for the ego-motion and remove the ground points. Then I should transform my data format to the one mentioned in PC Accumulation. Next, I run the main.sh (not demo.sh). Is this process correct? Or is there any quick start for this task?

**Comment by yanconglin** [comment]
1. Ego motion compendation first. 
2. Feed them to demo.py. I think this is way easier and only work is about a simple dataloader.
Depending on the task or exp setup, you can choose nearby frames only or every n frames (resulting in denser aggregated points) as shown in the paper.

**Comment by BotaoSun** [comment]
Thanks for your prompt reply.

I began from running 'demo.sh' with 'demo.npz'. But it was weird that I didn't change anything in the setup, and I ran the program in an NVIDIA A100 80GB for 20 minutes. It didn't report an error and was not complete (I think this program should complete within 20 minutes). I would like to know why this happens.

The following is the log:
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/d35312be-ddce-4166-8098-9036027a519f">

**Comment by yanconglin** [comment]
Unfortunately, I do not have access to A100s at this moment. it seems to be a slurm problem. I would suggest (speculation only) you check https://github.com/yanconglin/ICP-Flow/blob/19da224472b6e17216873bddb361af5cd85faa45/demo.py#L81, because there is so little information.

**Comment by BotaoSun** [comment]
Thanks for your reply. I try to find the reason for these two days, I found that the program stuck at https://github.com/yanconglin/ICP-Flow/blob/19da224472b6e17216873bddb361af5cd85faa45/demo.py#L218 no matter on HPC or on my PC. Have you ever met this problem before?

**Comment by BotaoSun** [comment]
> Thanks for your reply. I try to find the reason for these two days, I found that the program stuck at
> 
> https://github.com/yanconglin/ICP-Flow/blob/19da224472b6e17216873bddb361af5cd85faa45/demo.py#L218
> 
> no matter on HPC or on my PC. Have you ever met this problem before?

It is quite weird since I can move the point_src/point_dst to GPU, but not for label_src/label_dst

**Comment by yanconglin** [comment]
I have no clue. It does not make sense to me. 
I have never had this issue, either on local machines or HPC.

**Comment by BotaoSun** [comment]
Anyway, thanks a lot!
